name: Playwright Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
    - name: Setup corepack
      run: |
        echo "Before: corepack version => $(corepack --version || echo 'not installed')"
        npm install -g corepack@latest
        echo "After : corepack version => $(corepack --version)"
        corepack enable
        echo "pnpm version $(pnpm --version)"
    - name: log node & package manager
      run: 'printf "node -> %s\npnpm -> %s"  "$(node -v)" "$(pnpm -v)"'
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
    - name: Install Playwright Browsers
      run: pnpm exec playwright install --with-deps
    - name: Run Playwright tests
      run: pnpm exec playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
